Vagrant.configure("2") do |config|

config.vm.define "node-1" do |node1|
node1.vm.box = "centos/7"
node1.vm.network "private_network", ip: "192.168.33.1"
node1.vm.hostname = "node1.olivarius.com.br"

node1.vm.provider "virtualbox" do |vb|
vb.memory = "1024"
end

end

(2..3).each do |i|

config.vm.define "node-#{i}" do |node|
node.vm.box = "centos/7"
node.vm.network "private_network", ip: "192.168.33.#{i}"
node.vm.hostname = "node#{i}.olivarius.com.br"

node.vm.provider "virtualbox" do |vb|
vb.memory = "2048"
end
end
end

config.vm.provision "ansible" do |ansible|
ansible.playbook = "playbook.yml"

end
end
